name: Generate/Publish Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Gen/Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Build Docs
        run: |
          nix develop --command cargo doc --color=always --no-deps --all --all-features
          echo '<meta http-equiv="refresh" content="0; url=apex_rs/index.html">' >> target/doc/index.html
          echo '<a href="apex_rs/index.html">Redirect</a>' >> target/doc/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          branch: gh-pages
          path: target/doc
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
